deploy:
  provider: openshift
  user: clara.attermo@gmail.com
  password:
    secure: aIteLdft4ROZI4U8DMEl6R7PP37eA1QJqVpNCHbUlanjufQVGlrSN5ECQlaJ+QC+GW07Aofe0ipx1R98YoaUk0Gss2wyWZLsbeLtI70NFZos6/Jfmk441IBA2DIHmYDJMpdh/kImrD+m9QwCiWZjfwVjZGocqa0uZwMSJTI1ZizbjSlom0guGRtbmr71yBj6K6JJs8cDYS0whpugWSeZuH4/juVkrCnll9OU3TrSmZn1OT534JhLyBfZ6XcLZWMywlIni1vUu25R4nMvlvhlXGWhC491sV4r57oWg2dyffR9Zjsz0VgdZGZKWIvqfa3ZY5WpU2GFQnKSXtCetMrNoIUGJE2iB+OlZ4dMVZ/GxXWvOreOTDyBsJ3p9vRnFZDWwqxGMeStcg6EWnMd8rnzheP48c7RN3dS4Z8C31513EmppaHjt/ONptpnwmAbL+YTzwonod9+JwvBXd8pA7ciJoH9NAiBCP6VqpoWAQMmOgfdU1Bq3xJ7w9wieuJdGETH9n8grPVoT3znUYdyJU1ZxUEoIelz5Rt7jxCT9vDMpOMZXSgsYT9E34r3ymryY9aITkObQg3nA0Gxy63PzTYVQCFayVwrVZLYUzyXhDMOEP92OMW67pp5vgMqIcxrJa2qFwLEHVbLzdssYMUE8ct6iDUYV/ZUhsxzf0FlekMEBVQ=
  app: bandettes
  domain: cattermo
  on:
    repo: cattermo/bandettes
